### PR TITLE
sevral changes

### PR DESCRIPTION
**Pull request by ttv20**
- replace alert with non interrupt message
- fix style on mobile
- fix style of modal and login
- move segment box and source box to be together 
- make the textarea automatically grow when needed

### CODE REVIEW

**Comment by yairl** [comment]
Sorry for the delay in replying, I did not notice this PR.

How big will the text area be?
Can you quickly explain your other changes?

wrt alerts, can you put this in a function instead of modifying the field locally in every location?
Would make it easier to use for other alerts later on.

**Comment by ttv20** [comment]
השדה טקסט יגדל כדי להתאים לטקסט אבל לא יגרום לדף להיות עם גלילה
בפלאפון הדף יתפוס את כל הגובה ולא רק חלק והגבולות בצדדים יקטנו
הפופאפ של 'לא הצלחתי' יהיה יותר נמוך בפלאפון ובמרכוז תקין וישר ומחשב
מקטע ומקור יהיו באותה שורה כי רוב האנשים לא צריכים לדעת איזה מס' מקטע זה וזה תופס מקום לאורך (את זה אפשר לבטל)
במקום אלרט הוא כותב טקסט אדום מהבהב מעל הכפתורים שנעלם ברגע שלוחצים play שוב

**Comment by yairl** [comment]
1. I think it makes more sense to keep the header (loggied in as ... and statistics) centered.
2. Best to maintain order between the fields, even if they're in the same line: source | episode | segment (reversed in hebrew).
3.

**Comment by yairl** [comment]
Apologies for acting slowly.
If you can fix the conflicts, I'm happy to test and merge.

**Comment by nnrepos** [comment]
will this solve the hidden text problem when rotating the screen in mobile?
908697d4-f2cc-4bc2-822f-40559c6cd5b7

**Comment by yairl** [comment]
> will this solve the hidden text problem when rotating the screen in mobile? 908697d4-f2cc-4bc2-822f-40559c6cd5b7
> 
> @ttv20

I hope so, it's one of the issues I hate most.

**Comment by yairl** [comment]
@nnrepos feel like doing conflict resolution here so this one can proceed? :)

**Comment by nnrepos** [comment]
> @nnrepos feel like doing conflict resolution here so this one can proceed? :)

sure, do i have write access?

**Comment by nnrepos** [comment]
@yairl 
i am lost here - i don't have access to @ttv20's branch, therefore i can only create a new PR with their changes, and fix the conflicts in my copied branch, correct? is that your intention?

**Comment by yairl** [comment]
> @yairl i am lost here - i don't have access to @ttv20's branch, therefore i can only create a new PR with their changes, and fix the conflicts in my copied branch, correct? is that your intention?

Yes.

**Comment by nnrepos** [comment]
i cherry-picked this into a new branch. when i tested it, i found that on some low-resolution devices (e.g. iPhone SE, Surface Duo) the buttons are pushed out of the main body:
image

i'm not good enough at CSS to fix this issue, therefore i'm not creating a PR.
@ttv20 feel free to fix this and resolve conflicts

**Comment by yairl** [comment]
Unhandled for a long time - closing.

**Pull request closed without merging**
